import os from "node:os";
import path from "node:path";
import type { EngineConfig } from "./schema.js";

/**
 * Built-in defaults. Endpoint lists and price tables live here as DATA so that
 * nothing model-specific is hard-coded in the engine logic. Users override any
 * of this in config.local.json.
 */
export function defaultConfig(): EngineConfig {
  return {
    homeDir: path.join(os.homedir(), ".multi-model-team"),
    providers: {
      endpoints: [
        {
          id: "anthropic",
          providerId: "anthropic",
          displayName: "Anthropic (Claude)",
          baseUrl: "https://api.anthropic.com",
          protocol: "anthropic",
          envKeys: ["ANTHROPIC_API_KEY"],
        },
        {
          id: "openai",
          providerId: "openai",
          displayName: "OpenAI",
          baseUrl: "https://api.openai.com/v1",
          protocol: "openai-responses",
          envKeys: ["OPENAI_API_KEY"],
        },
        {
          id: "xai",
          providerId: "xai",
          displayName: "xAI (Grok)",
          baseUrl: "https://api.x.ai/v1",
          protocol: "openai-responses",
          envKeys: ["XAI_API_KEY"],
        },
        {
          id: "zai-general",
          providerId: "zai",
          displayName: "Z.AI (GLM) general",
          baseUrl: "https://api.z.ai/api/paas/v4",
          protocol: "openai-chat",
          envKeys: ["ZAI_API_KEY", "ZHIPU_API_KEY"],
        },
        {
          id: "zai-coding",
          providerId: "zai",
          displayName: "Z.AI (GLM) coding plan",
          baseUrl: "https://api.z.ai/api/coding/paas/v4",
          protocol: "openai-chat",
          envKeys: ["ZAI_API_KEY", "ZHIPU_API_KEY", "ZAI_CODING_API_KEY"],
        },
        {
          id: "zai-cn",
          providerId: "zai",
          displayName: "Z.AI (GLM) mainland China (bigmodel.cn)",
          baseUrl: "https://open.bigmodel.cn/api/paas/v4",
          protocol: "openai-chat",
          envKeys: ["ZAI_API_KEY", "ZHIPU_API_KEY", "BIGMODEL_API_KEY"],
        },
        {
          id: "moonshot",
          providerId: "moonshot",
          displayName: "Moonshot (Kimi) international",
          baseUrl: "https://api.moonshot.ai/v1",
          protocol: "openai-chat",
          envKeys: ["MOONSHOT_API_KEY", "KIMI_API_KEY"],
        },
        {
          id: "claude-code",
          providerId: "anthropic",
          displayName: "Claude Code CLI (subscription login)",
          baseUrl: "cli://claude",
          protocol: "claude-cli",
          envKeys: [],
        },
        {
          id: "moonshot-cn",
          providerId: "moonshot",
          displayName: "Moonshot (Kimi) China",
          baseUrl: "https://api.moonshot.cn/v1",
          protocol: "openai-chat",
          envKeys: ["MOONSHOT_API_KEY", "KIMI_API_KEY"],
        },
      ],
      extraCompatible: [],
      allowProbes: true,
      cacheTtlHours: 24,
      excludeModels: ["embedding", "tts", "whisper", "dall-e", "image", "audio", "realtime", "moderation", "transcribe", "search-preview", "babbage", "davinci", "computer-use", "ocr", "glm-4-32b"],
      fallbackModels: {
        zai: ["glm-4.5-air", "glm-5-turbo", "glm-5.3-flash", "glm-4.6", "glm-4.5-flash"],
        moonshot: ["kimi-k2.6", "kimi-k3"],
      },
      // Claude Code CLI transport: no models endpoint without an API key, so the table is static.
      // Capabilities per docs/providers.md; `claude --effort` accepted low..max on every model when tested (2026-09-26, CLI 2.1.283).
      claudeCliModels: [
        { id: "claude-fable-5-1", displayName: "Claude Fable 5.1", vision: true, contextWindow: 1_000_000, maxOutputTokens: 128_000, effortLevels: ["low", "medium", "high", "xhigh", "max"] },
        { id: "claude-opus-5-5", displayName: "Claude Opus 5.5", vision: true, contextWindow: 1_000_000, maxOutputTokens: 128_000, effortLevels: ["low", "medium", "high", "xhigh", "max"] },
        { id: "claude-sonnet-5", displayName: "Claude Sonnet 5", vision: true, contextWindow: 1_000_000, maxOutputTokens: 128_000, effortLevels: ["low", "medium", "high", "xhigh", "max"] },
        { id: "claude-haiku-4-5", displayName: "Claude Haiku 4.5", vision: true, contextWindow: 200_000, maxOutputTokens: 64_000, effortLevels: ["low", "medium", "high", "xhigh", "max"] },
      ],
    },
    // USD per million tokens. Data from docs/providers.md (2026-09-26); regex keys, first match wins after exact ids.
    pricing: {
      "anthropic/claude-fable-5-1": { inputPerMillion: 10, outputPerMillion: 50, cachedInputPerMillion: 0.25 },
      "anthropic/claude-fable-5": { inputPerMillion: 10, outputPerMillion: 50, cachedInputPerMillion: 1 },
      "anthropic/claude-opus-5-5": { inputPerMillion: 4, outputPerMillion: 20, cachedInputPerMillion: 0.2 },
      "anthropic/claude-opus-5": { inputPerMillion: 5, outputPerMillion: 25, cachedInputPerMillion: 0.5 },
      "anthropic/claude-opus-4-[678].*": { inputPerMillion: 5, outputPerMillion: 25, cachedInputPerMillion: 0.5 },
      "anthropic/claude-opus-4-5.*": { inputPerMillion: 5, outputPerMillion: 25, cachedInputPerMillion: 0.5 },
      "anthropic/claude-sonnet-5": { inputPerMillion: 2, outputPerMillion: 10, cachedInputPerMillion: 0.2 },
      "anthropic/claude-sonnet-4-.*": { inputPerMillion: 3, outputPerMillion: 15, cachedInputPerMillion: 0.3 },
      "anthropic/claude-haiku-4-5.*": { inputPerMillion: 1, outputPerMillion: 5, cachedInputPerMillion: 0.1 },
      "openai/gpt-6-astra": { inputPerMillion: 10, outputPerMillion: 50, cachedInputPerMillion: 1 },
      "openai/gpt-6-sol": { inputPerMillion: 2, outputPerMillion: 10, cachedInputPerMillion: 0.2 },
      "openai/gpt-6-luna": { inputPerMillion: 0.1, outputPerMillion: 0.5, cachedInputPerMillion: 0.01 },
      "openai/gpt-5\\.6-sol": { inputPerMillion: 4, outputPerMillion: 20, cachedInputPerMillion: 0.4 },
      "openai/gpt-5\\.6-terra": { inputPerMillion: 2, outputPerMillion: 12, cachedInputPerMillion: 0.2 },
      "openai/gpt-5\\.6-luna": { inputPerMillion: 0.2, outputPerMillion: 1.2, cachedInputPerMillion: 0.02 },
      "openai/gpt-5\\.5": { inputPerMillion: 5, outputPerMillion: 30, cachedInputPerMillion: 0.5 },
      "openai/gpt-5\\.4-mini": { inputPerMillion: 0.75, outputPerMillion: 4.5, cachedInputPerMillion: 0.075 },
      "openai/gpt-5\\.4-nano": { inputPerMillion: 0.2, outputPerMillion: 1.25, cachedInputPerMillion: 0.02 },
      "openai/gpt-5\\.4": { inputPerMillion: 2.5, outputPerMillion: 15, cachedInputPerMillion: 0.25 },
      "openai/gpt-5\\.2": { inputPerMillion: 1.75, outputPerMillion: 14, cachedInputPerMillion: 0.175 },
      "openai/gpt-5(\\.1)?": { inputPerMillion: 1.25, outputPerMillion: 10, cachedInputPerMillion: 0.125 },
      "openai/gpt-5-mini": { inputPerMillion: 0.25, outputPerMillion: 2, cachedInputPerMillion: 0.025 },
      "openai/gpt-5-nano": { inputPerMillion: 0.05, outputPerMillion: 0.4, cachedInputPerMillion: 0.005 },
      "openai/gpt-4\\.1": { inputPerMillion: 2, outputPerMillion: 8, cachedInputPerMillion: 0.5 },
      "openai/gpt-4\\.1-mini": { inputPerMillion: 0.4, outputPerMillion: 1.6, cachedInputPerMillion: 0.1 },
      "openai/gpt-4\\.1-nano": { inputPerMillion: 0.1, outputPerMillion: 0.4, cachedInputPerMillion: 0.025 },
      "openai/o3": { inputPerMillion: 2, outputPerMillion: 8, cachedInputPerMillion: 0.5 },
      "openai/o4-mini": { inputPerMillion: 1.1, outputPerMillion: 4.4, cachedInputPerMillion: 0.275 },
      "openai/o3-mini": { inputPerMillion: 1.1, outputPerMillion: 4.4, cachedInputPerMillion: 0.55 },
      "xai/grok-4\\.[67].*": { inputPerMillion: 2, outputPerMillion: 6, cachedInputPerMillion: 0.5 },
      "xai/grok-4\\.5.*": { inputPerMillion: 2, outputPerMillion: 6, cachedInputPerMillion: 0.3 },
      "xai/grok-4\\.(3|20).*": { inputPerMillion: 1.25, outputPerMillion: 2.5, cachedInputPerMillion: 0.2 },
      "xai/grok-build.*|xai/grok-code-fast.*": { inputPerMillion: 1, outputPerMillion: 2, cachedInputPerMillion: 0.2 },
      "zai/glm-5\\.3-flashx": { inputPerMillion: 0.37, outputPerMillion: 1.25, cachedInputPerMillion: 0.075 },
      "zai/glm-5\\.3-flash": { inputPerMillion: 0.15, outputPerMillion: 0.5, cachedInputPerMillion: 0.03 },
      "zai/glm-5\\.[123]": { inputPerMillion: 1.4, outputPerMillion: 4.4, cachedInputPerMillion: 0.26 },
      "zai/glm-5(-turbo)?": { inputPerMillion: 1, outputPerMillion: 3.2, cachedInputPerMillion: 0.2 },
      "zai/glm-4\\.7-flashx": { inputPerMillion: 0.07, outputPerMillion: 0.4, cachedInputPerMillion: 0.01 },
      "zai/glm-4\\.[57]-flash": { inputPerMillion: 0, outputPerMillion: 0 },
      "zai/glm-4\\.[67]": { inputPerMillion: 0.6, outputPerMillion: 2.2, cachedInputPerMillion: 0.11 },
      "zai/glm-4\\.5-airx": { inputPerMillion: 1.1, outputPerMillion: 4.5, cachedInputPerMillion: 0.22 },
      "zai/glm-4\\.5-air": { inputPerMillion: 0.2, outputPerMillion: 1.1, cachedInputPerMillion: 0.03 },
      "zai/glm-4\\.5-x": { inputPerMillion: 2.2, outputPerMillion: 8.9, cachedInputPerMillion: 0.45 },
      "zai/glm-4\\.5": { inputPerMillion: 0.6, outputPerMillion: 2.2, cachedInputPerMillion: 0.11 },
      "zai/glm-4\\.6v-flashx": { inputPerMillion: 0.04, outputPerMillion: 0.4, cachedInputPerMillion: 0.004 },
      "zai/glm-4\\.6v-flash": { inputPerMillion: 0, outputPerMillion: 0 },
      "zai/glm-4\\.6v": { inputPerMillion: 0.3, outputPerMillion: 0.9, cachedInputPerMillion: 0.05 },
      "zai/glm-4\\.5v": { inputPerMillion: 0.6, outputPerMillion: 1.8, cachedInputPerMillion: 0.11 },
      "moonshot/kimi-k3": { inputPerMillion: 3, outputPerMillion: 15, cachedInputPerMillion: 0.3 },
      "moonshot/kimi-k2\\.7-code-highspeed": { inputPerMillion: 1.9, outputPerMillion: 8, cachedInputPerMillion: 0.38 },
      "moonshot/kimi-k2\\.7-code": { inputPerMillion: 0.95, outputPerMillion: 4, cachedInputPerMillion: 0.19 },
      "moonshot/kimi-k2\\.6": { inputPerMillion: 0.95, outputPerMillion: 4, cachedInputPerMillion: 0.16 },
    },
    // Static facts the providers' model endpoints do not report. Metadata and probes take precedence.
    capabilityHints: {
      "zai/glm-5\\.[0-3].*": { contextWindow: 1_000_000, maxOutputTokens: 128_000 },
      "zai/glm-4\\.[67]$": { contextWindow: 200_000, maxOutputTokens: 128_000 },
      "zai/glm-4\\.5.*": { contextWindow: 128_000, maxOutputTokens: 96_000 },
      "zai/glm-4\\.[56]v.*": { contextWindow: 128_000, vision: true },
      "openai/gpt-(5\\.[4-6]|6).*": { contextWindow: 1_050_000, maxOutputTokens: 128_000, vision: true },
      "openai/gpt-5(\\.[12])?(-mini|-nano)?": { contextWindow: 400_000, maxOutputTokens: 128_000, vision: true },
      "openai/gpt-4\\.1.*": { contextWindow: 1_047_576, maxOutputTokens: 32_768, vision: true },
      "openai/o[34](-mini)?": { contextWindow: 200_000, maxOutputTokens: 100_000, vision: true },
    },
    pipeline: {
      maxDiscussionRounds: 6,
      maxMeetingRounds: 3,
      stallLimit: 3,
      parallelTests: true,
      flakeRerun: true,
      flakeRerunMaxSec: 120,
      redTeamMaxTargets: 0,
      harvest: true,
      wildcard: true,
      maxToolIterations: 25,
      contextBudgetTokens: 60_000,
      minMembers: 2,
      defaultReasoning: "medium",
      maxTokensPerCall: 8192,
      callTimeoutMs: 300_000,
      retries: 3,
    },
    cost: { capUsd: null },
    safety: {
      maxResourceFraction: 0.6,
      heavyRamMb: 2048,
      commandTimeoutMs: 600_000,
      hardRssLimitMb: 0,
      heavyCommandPatterns: [
        "\\b(npm|pnpm|yarn|bun)\\s+(install|i|ci|add)\\b",
        "\\bpip3?\\s+install\\b",
        "\\b(cargo|go|dotnet|mvn|gradle|make|cmake|ninja)\\s+(build|install|test)?\\b",
        "\\bdocker\\b",
        "\\b(python3?|torch|accelerate|ollama|llama|vllm)\\b.*\\b(train|finetune|fine-tune|serve|run)\\b",
        "\\bwget\\b|\\bcurl\\b.*\\s-[oO]\\b",
        "\\bffmpeg\\b",
      ],
      osSandbox: "auto",
      sandboxWriteAllow: [],
      sandboxReadDeny: [],
      destructivePatterns: [
        "\\brm\\s+(-[a-zA-Z]*[rf][a-zA-Z]*\\s+)+",
        "\\brmdir\\b",
        "\\b(del|erase|rd)\\s+(/[sq]\\s+)+",
        "Remove-Item\\b",
        "\\bmkfs\\b|\\bdiskutil\\s+erase|\\bformat\\s+[a-z]:",
        "\\b(sudo|doas)\\b",
        "\\b(apt(-get)?|brew|choco|winget|dnf|yum|pacman)\\s+(remove|uninstall|purge)\\b",
        "\\b(npm|pnpm|yarn|pip3?)\\s+(uninstall|remove)\\s+(-g|--global)",
        "\\bgit\\s+(push\\s+.*--force|reset\\s+--hard|clean\\s+-[a-z]*f)",
        "\\bdefaults\\s+write\\b|\\breg\\s+(add|delete)\\b|\\bsystemctl\\b|\\blaunchctl\\b",
        "\\bchmod\\s+(-R\\s+)?[0-7]*777\\b|\\bchown\\s+-R\\b",
        ">\\s*/dev/sd|\\bdd\\s+if=",
        "\\bkill(all)?\\s+-9\\b|\\btaskkill\\b",
        "\\bshutdown\\b|\\breboot\\b",
        // Write-capable commands: only require confirmation when aimed outside the sandbox (the classifier checks paths).
        "\\b(mv|cp|rsync|tee|ln|install|dd|scp|xcopy|robocopy|copy|move|ren)\\b",
        "\\bgit\\s+push\\b|\\bnpm\\s+publish\\b|\\bpip\\s+upload\\b|\\bcargo\\s+publish\\b",
        ">{1,2}\\s*(/|~|[A-Za-z]:\\\\)",
      ],
    },
    search: { provider: "mock", envKey: "SEARCH_API_KEY", maxResults: 5 },
    ui: { host: "127.0.0.1", port: 4310, openBrowser: true },
    workTypes: { extraDirs: [] },
  };
}
